# Uses 
# - https://github.com/treosh/lighthouse-ci-action

# Based on https://github.com/tomdye/vercel-lighthouse-action/blob/main/workflows/pr-deploy-and-audit.yml

name: Lighthouse-CI

on: [push]
  # pull_request:
  #   branches:
  #     - main
  #     - lighthouse

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate URLs
        id: urls
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const res = await fetch(`https://calla-lily-git-lighthouse-other-people.vercel.app/api/site-urls.json`, {
              headers: {
                'Content-Type': 'application/json'
              }
            });
            const data = await res.json();
            const batch = data.urls.filter((url) => {return url.includes('skin')});
            core.setOutput('urls', batch.join('\n'))

# const urlListString = data.urls.join('\n')
# core.setOutput('urls', urlListString)

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v10
        id: lighthouse_audit
        with:
          urls: ${{ steps.urls.outputs.urls }}
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage

      - name: Save Results Into Release
        run: echo ${{ steps.lighthouse_audit.outputs.manifest }} > release.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release.txt