# Uses 
# - https://github.com/zentered/vercel-preview-url
# - https://github.com/treosh/lighthouse-ci-action

# Based on https://github.com/tomdye/vercel-lighthouse-action/blob/main/workflows/pr-deploy-and-audit.yml

name: Lighthouse-CI

on: [push]

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - run: sleep 180
      # - name: vercel-preview-url
      #   uses: zentered/vercel-preview-url@v1.1.9
      #   id: vercel_preview_url
      #   env:
      #     VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      #   with:
      #     vercel_team_id:  ${{ secrets.VERCEL_TEAM_ID }}
      #     vercel_project_id: ${{ secrets.SITE_VERCEL_PROJECT_ID }}
          
      # - name: Get URL
      #   run: echo ${{ steps.vercel_preview_url.outputs.preview_url }}

      - name: Generate URLs
        id: urls
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            import fetch from 'node-fetch';

            const res = await fetch(`https://calla-lily-git-lighthouse-other-people.vercel.app/api/site-urls.json`, {
              headers: {
                'Content-Type': 'application/json'
              }
            });

            const data = res.json();
            console.log(data)
            core.setOutput('urls', data.urls)

      - run: echo ${{ steps.urls.outputs.urls }}

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v10
        id: lighthouse_audit
        with:
          urls: "https://${{ steps.vercel_preview_url.outputs.preview_url }}"
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage

      - name: Output Results
        run: echo ${{ steps.lighthouse_audit.outputs.links }}