name: Recommender Auto-Generation

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - recommender-cli

jobs:
  recommender:
    name: Recommendation Model
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Recommendation repo
        uses: actions/checkout@v4
        with:
          repository: Other-People-UCSD/recommender
          path: recommender
    
      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
      
      - name: run test notebook
        run: python recommender/test.py

      # - name: View files in workspace
      #   run: ls -lR ${{github.workspace}}

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: output.json

      - name: Checkout Calla-Lily repo
        uses: actions/checkout@v4
        with:
          path: calla-lily
          ref: recommender-cli

      - name: View files in workspace
        run: |
          ls -l ${{github.workspace}}
          ls -l ${{github.workspace}}/calla-lily/data

      - name: Push output file to this branch's data directory
        run: |
          cp output.json calla-lily/data
          cd calla-lily
          git config user.name otherpeopleucsd
          git config user.email otherpeoplesd@gmail.com
          git add output.json
          git commit -m "Autogenerated recommendation results"
          git push