name: Recommender Auto-Generation

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - recommender-cli

jobs:
  recommender:
    name: Recommendation Model
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Calla-Lily repo
        uses: actions/checkout@v4
        with:
          path: calla-lily

      - name: Checkout Recommendation repo
        uses: actions/checkout@v4
        with:
          repository: Other-People-UCSD/recommender
          path: recommender
    
      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'

      - name: Install Python Dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r recommender/requirements.txt

      - name: Run test-deps script
        run: python recommender/test.py

      # - name: Copy recommender.json to data directory
      #   run: |
      #     cp recommender.json calla-lily/data

      # - name: Push output file to this branch's data directory
      #   run: |
      #     cd calla-lily
      #     git status
      #     git config user.name "Github Actions[bot]"
      #     git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     git add ./data/recommender.json
      #     git status
      #     git commit -m "Autogenerated recommendation results"
      #     git push

      # - name: Upload results
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: test-results
      #     path: recommender.json