name: Recommender Auto-Generation

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - recommender-cli

jobs:
  recommender:
    name: Recommendation Model
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Recommendation repo
        uses: actions/checkout@v4
        with:
          repository: Other-People-UCSD/recommender
          path: recommender
    
      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
      
      - name: run test notebook
        run: python recommender/test.ipynb

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: recommender/output.json