name: Recommender Auto-Generation

# Activate this workflow only if published pages have been modified.
# This will prevent redundant recommendations and extraneous commits 
# when modifying the rest of the website
on:
  push:
    paths:
      - 'posts/**'

jobs:
  recommender:
    name: Recommendation Model
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Calla-Lily repo
        uses: actions/checkout@v4
        with:
          path: Calla-Lily

      - name: Checkout Recommendation repo
        uses: actions/checkout@v4
        with:
          repository: Other-People-UCSD/recommender
          path: recommender

      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'

      - name: Install Python Dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r recommender/requirements.txt

      - name: Run Recommendation Model script
        run: python recommender/recommendation-v1.0.py

# The workflow environment looks like this
# .
# Calla-Lily/
# recommender/
# recommender.json (the output from running the recommender.py script)

  # Set date to compare recs to previous versions
      - name: Set Date with Commit Hash 
        id: date
        run: |
          datehash="$(date +'%Y-%m-%d')-$(git rev-parse --short '$GITHUB_SHA')"
          echo "::set-output name=datehash::$datehash"

# First command sends the output to website
# Second command creates and renames the file to be outputted as workflow artifact
      - name: Copy recommender.json to data directory
        run: |
          cp ./recommender-auto.json ./Calla-Lily/data/recommender.json
          cp recommender-auto.json recommender-${{ steps.date.outputs.datehash}}.json

      - name: Push output file to this branch's data directory
        run: |
          cd Calla-Lily
          git status
          git config user.name "Github Actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ./data/recommender.json
          git status
          git commit -m "Autogenerated recommendation results"
          git push

      - name: Upload Recommendation Results
        uses: actions/upload-artifact@v3
        with:
          name: recommendation-results-v1.0
          path: recommender-${{ steps.date.outputs.datehash}}.json