name: Recommender Auto-Generation

# Activate this workflow only if published pages have been modified.
# This will prevent redundant recommendations and extraneous commits 
# when modifying the rest of the website
on:
  pull_request:
    branches: [ main ]
    paths:
      - '_posts/**'
  workflow_dispatch: 
  # Manually run if manually uploading the artifact to the repo. 
  # Due to branch protections, pull request trigger is the only way to automatically upload results.

jobs:
  recommender:
    name: Recommendation Model
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Calla-Lily repo
        uses: actions/checkout@v4
        with:
          path: Calla-Lily

      - name: Checkout Recommendation repo
        uses: actions/checkout@v4
        with:
          repository: Other-People-UCSD/recommender
          path: recommender

      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'

      - name: Install Python Dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r recommender/requirements.txt

      - name: Run Recommendation Model script
        run: python recommender/recommendation-v1.0.py

# The workflow environment looks like this
# .
# Calla-Lily/
# recommender/
# recommender-auto.json (the output from running the recommender.py script)

# Set date to compare recs to previous versions
# Final command creates and renames the file to be outputted as workflow artifact
      - name: Set Date
        id: date
        run: |
          date="$(date +'%Y-%m-%d')"
          echo "::set-output name=date::$date"
          echo "date=$date" >> $GITHUB_OUTPUT

# First command sends the output to website
      - name: Copy recommender.json to data directory
        run: |
          cp ./recommender-auto.json ./Calla-Lily/data/recommender.json
          cp recommender-auto.json recommender-${{ steps.date.outputs.date }}.json

# Runner is currently in ./Calla-lily from last step
      - name: Push output file to this branch's data directory
        continue-on-error: true # If recs are the same from before, skip redundant commit
        run: |
          cd Calla-Lily
          git status
          git config user.name "Github Actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ./data/recommender.json
          git status
          git commit -m "Autogenerated recommendation results"
          git push

      - name: Upload Recommendation Results
        uses: actions/upload-artifact@v3
        with:
          name: recommendation-results-${{ steps.date.outputs.date }}
          path: recommender-${{ steps.date.outputs.date }}.json